# Generated by Django 3.0.1 on 2020-01-04 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200103_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='author',
            field=models.CharField(default='Anonymous', max_length=200),
        ),
    ]
